#!/bin/bash

APTCHECK=/usr/lib/update-notifier/apt-check

rm -f updates security_updates

if [ ! -f ${APTCHECK} ]
then
    exit
fi

RET=$(${APTCHECK} 2>&1)

# updates
echo $RET | cut -d";" -f1 > updates
# security updates
echo $RET | cut -d";" -f2 > security_updates
